USE DATABASE REALTIME_ANALYTICS;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS FACT_SECURITY_EVENTS (
  event_id STRING,
  event_time STRING,
  event_timestamp TIMESTAMP_NTZ,
  ingestion_timestamp TIMESTAMP_NTZ,
  event_type STRING,
  action STRING,
  actor_id STRING,
  actor_email STRING,
  actor_role STRING,
  actor_department STRING,
  is_privileged_actor BOOLEAN,
  session_id STRING,
  source_ip STRING,
  source_country STRING,
  device_type STRING,
  user_agent STRING,
  target_system STRING,
  target_resource STRING,
  auth_method STRING,
  mfa_used BOOLEAN,
  outcome STRING,
  http_status NUMBER,
  bytes_out NUMBER,
  failed_attempts_1h NUMBER,
  request_rate_1m NUMBER,
  detection_source STRING,
  is_test_event BOOLEAN,
  source_system STRING,
  event_hour NUMBER,
  is_valid_event_type BOOLEAN,
  is_valid_outcome BOOLEAN,
  is_valid_actor BOOLEAN,
  is_valid_target BOOLEAN,
  is_valid_bytes BOOLEAN,
  is_valid_status BOOLEAN,
  quality_status STRING,
  quality_failure_reason STRING,
  threat_reason STRING,
  is_anomaly BOOLEAN,
  severity STRING,
  severity_rank NUMBER,
  mitre_tactic STRING,
  topic STRING,
  kafka_partition NUMBER,
  kafka_offset NUMBER,
  kafka_timestamp TIMESTAMP_NTZ,
  batch_id NUMBER
);

-- Quarantine table for records that fail schema/quality validation.
CREATE TABLE IF NOT EXISTS ERROR_SECURITY_EVENTS LIKE FACT_SECURITY_EVENTS;

CREATE TABLE IF NOT EXISTS AGG_SECURITY_METRICS_1M (
  window_start TIMESTAMP_NTZ,
  window_end TIMESTAMP_NTZ,
  event_type STRING,
  target_system STRING,
  source_country STRING,
  event_count NUMBER,
  failure_count NUMBER,
  blocked_count NUMBER,
  failure_rate FLOAT,
  unique_actors NUMBER,
  unique_source_ips NUMBER,
  total_bytes_out NUMBER,
  anomaly_count NUMBER,
  max_severity_rank NUMBER,
  batch_id NUMBER
);

CREATE TABLE IF NOT EXISTS AI_THREAT_INSIGHTS (
  insight_id STRING,
  generated_at TIMESTAMP_NTZ,
  event_timestamp TIMESTAMP_NTZ,
  event_id STRING,
  event_type STRING,
  actor_id STRING,
  actor_role STRING,
  target_system STRING,
  source_ip STRING,
  source_country STRING,
  outcome STRING,
  bytes_out NUMBER,
  failed_attempts_1h NUMBER,
  request_rate_1m NUMBER,
  threat_reason STRING,
  severity STRING,
  mitre_tactic STRING,
  risk_score NUMBER,
  risk_level STRING,
  threat_explanation STRING,
  recommended_action STRING,
  triage_queue STRING,
  model_provider STRING
);
